INFO     root:HTMLParser.py:16 Got all the links from the link
INFO     root:test_html_parser.py:19 test_get_links_returns_list
INFO     root:test_html_parser.py:29 test_len_list_of_links_more_than_0
INFO     root:HTMLParser.py:16 Got all the links from the link
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'google': No scheme supplied. Perhaps you meant https://google?
ERROR    root:HTMLParser.py:19 Error executing the request: Invalid URL 'google': No scheme supplied. Perhaps you meant https://google?
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'google': No scheme supplied. Perhaps you meant https://google?
INFO     root:test_html_parser.py:47 test_invalid_url
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
ERROR    root:HTMLParser.py:19 Error executing the request: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'google.com': No scheme supplied. Perhaps you meant https://google.com?
INFO     root:test_html_parser.py:47 test_invalid_url
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'www.google.com': No scheme supplied. Perhaps you meant https://www.google.com?
ERROR    root:HTMLParser.py:19 Error executing the request: Invalid URL 'www.google.com': No scheme supplied. Perhaps you meant https://www.google.com?
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'www.google.com': No scheme supplied. Perhaps you meant https://www.google.com?
INFO     root:test_html_parser.py:47 test_invalid_url
ERROR    root:HTMLParser.py:27 Error executing the request: HTTPSConnectionPool(host='www.google.', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104105e50>: Failed to resolve 'www.google' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR    root:HTMLParser.py:19 Error executing the request: HTTPSConnectionPool(host='www.google.', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104105e50>: Failed to resolve 'www.google' ([Errno 8] nodename nor servname provided, or not known)"))
ERROR    root:HTMLParser.py:27 Error executing the request: HTTPSConnectionPool(host='www.google.', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104104210>: Failed to resolve 'www.google' ([Errno 8] nodename nor servname provided, or not known)"))
INFO     root:test_html_parser.py:47 test_invalid_url
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'http//google.com': No scheme supplied. Perhaps you meant https://http//google.com?
ERROR    root:HTMLParser.py:19 Error executing the request: Invalid URL 'http//google.com': No scheme supplied. Perhaps you meant https://http//google.com?
ERROR    root:HTMLParser.py:27 Error executing the request: Invalid URL 'http//google.com': No scheme supplied. Perhaps you meant https://http//google.com?
INFO     root:test_html_parser.py:47 test_invalid_url
INFO     root:test_interface.py:19 test_welcome_message
INFO     root:test_interface.py:35 test_options
INFO     root:test_interface.py:51 test_invalid_option
INFO     root:HTMLParser.py:16 Got all the links from the link
INFO     root:validator.py:25 Valid link: https://www.google.com/imghp?hl=uk&tab=wi
INFO     root:validator.py:25 Valid link: https://maps.google.com.ua/maps?hl=uk&tab=wl
INFO     root:validator.py:25 Valid link: https://play.google.com/?hl=uk&tab=w8
INFO     root:validator.py:25 Valid link: https://www.youtube.com/?tab=w1
INFO     root:validator.py:25 Valid link: https://news.google.com/?tab=wn
INFO     root:validator.py:25 Valid link: https://mail.google.com/mail/?tab=wm
INFO     root:validator.py:25 Valid link: https://drive.google.com/?tab=wo
INFO     root:validator.py:25 Valid link: https://www.google.com.ua/intl/uk/about/products?tab=wh
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/history/optout?hl=uk
INFO     root:validator.py:25 Valid link: https://accounts.google.com/ServiceLogin?hl=uk&passive=true&continue=https://www.google.com/&ec=GAZAAQ
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/intl/uk/services/
INFO     root:validator.py:25 Valid link: https://www.google.com/setprefdomain?prefdom=UA&prev=https://www.google.com.ua/&sig=K_I9bCBCDr59OXQK8-2tXufYiTuFU%3D
INFO     root:interface.py:63 All valid links are recorded in the file 'valid_links.txt'
INFO     root:interface.py:64 Written all invalid links in the file 'broken_links.txt'
INFO     root:test_interface.py:68 test_html_option
INFO     root:HTMLParser.py:16 Got all the links from the link
INFO     root:validator.py:25 Valid link: https://www.google.com/imghp?hl=uk&tab=wi
INFO     root:validator.py:25 Valid link: https://maps.google.com.ua/maps?hl=uk&tab=wl
INFO     root:validator.py:25 Valid link: https://play.google.com/?hl=uk&tab=w8
INFO     root:validator.py:25 Valid link: https://www.youtube.com/?tab=w1
INFO     root:validator.py:25 Valid link: https://news.google.com/?tab=wn
INFO     root:validator.py:25 Valid link: https://mail.google.com/mail/?tab=wm
INFO     root:validator.py:25 Valid link: https://drive.google.com/?tab=wo
INFO     root:validator.py:25 Valid link: https://www.google.com.ua/intl/uk/about/products?tab=wh
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/history/optout?hl=uk
INFO     root:validator.py:25 Valid link: https://accounts.google.com/ServiceLogin?hl=uk&passive=true&continue=https://www.google.com/&ec=GAZAAQ
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/intl/uk/services/
INFO     root:validator.py:25 Valid link: https://www.google.com/setprefdomain?prefdom=UA&prev=https://www.google.com.ua/&sig=K_uQeIO5ZCbic2J6vZslRQQEjf6Vo%3D
INFO     root:interface.py:63 All valid links are recorded in the file 'valid_links.txt'
INFO     root:interface.py:64 Written all invalid links in the file 'broken_links.txt'
INFO     root:test_interface.py:84 test_invalid_html_link
INFO     root:PDFParser.py:26 Received all links from the pdf file
WARNING  root:validator.py:31 Invalid link: https://translater.google.com/
INFO     root:validator.py:25 Valid link: https://lms.ithillel.ua/
INFO     root:validator.py:25 Valid link: https://pypi.org/project/lorem
INFO     root:validator.py:25 Valid link: https://gorest.co.in/
WARNING  root:validator.py:31 Invalid link: https://uk.lipsum.cor/
WARNING  root:validator.py:31 Invalid link: https://www.cloudskillsboostd.google/journeys
WARNING  root:validator.py:31 Invalid link: https://www.linkedintoqa.com/feed/
INFO     root:validator.py:25 Valid link: https://docs.pytest.org/en/7.3.x/
WARNING  root:validator.py:28 Invalid link: https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D
WARNING  root:validator.py:31 Invalid link: https://www.dyoutuber.com/
WARNING  root:validator.py:31 Invalid link: https://www.olx.uar/uk/
WARNING  root:validator.py:31 Invalid link: https://githurbar.com/
INFO     root:validator.py:25 Valid link: https://medium.com/
INFO     root:validator.py:25 Valid link: https://metanit.com/python/tutorial/6.5.php
INFO     root:validator.py:25 Valid link: https://www.olx.ua/uk
INFO     root:interface.py:63 All valid links are recorded in the file 'valid_links.txt'
INFO     root:interface.py:64 Written all invalid links in the file 'broken_links.txt'
INFO     root:test_interface.py:101 test_pdf_option
INFO     root:PDFParser.py:26 Received all links from the pdf file
WARNING  root:validator.py:31 Invalid link: https://translater.google.com/
INFO     root:validator.py:25 Valid link: https://lms.ithillel.ua/
INFO     root:validator.py:25 Valid link: https://pypi.org/project/lorem
INFO     root:validator.py:25 Valid link: https://gorest.co.in/
WARNING  root:validator.py:31 Invalid link: https://uk.lipsum.cor/
WARNING  root:validator.py:31 Invalid link: https://www.cloudskillsboostd.google/journeys
WARNING  root:validator.py:31 Invalid link: https://www.linkedintoqa.com/feed/
INFO     root:validator.py:25 Valid link: https://docs.pytest.org/en/7.3.x/
WARNING  root:validator.py:28 Invalid link: https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D
WARNING  root:validator.py:31 Invalid link: https://www.dyoutuber.com/
WARNING  root:validator.py:31 Invalid link: https://www.olx.uar/uk/
WARNING  root:validator.py:31 Invalid link: https://githurbar.com/
INFO     root:validator.py:25 Valid link: https://medium.com/
INFO     root:validator.py:25 Valid link: https://metanit.com/python/tutorial/6.5.php
INFO     root:validator.py:25 Valid link: https://www.olx.ua/uk
INFO     root:interface.py:63 All valid links are recorded in the file 'valid_links.txt'
INFO     root:interface.py:64 Written all invalid links in the file 'broken_links.txt'
INFO     root:test_interface.py:117 test_invalid_pdf_path
INFO     root:HTMLParser.py:16 Got all the links from the link
INFO     root:validator.py:25 Valid link: https://www.google.com/imghp?hl=uk&tab=wi
INFO     root:validator.py:25 Valid link: https://maps.google.com.ua/maps?hl=uk&tab=wl
INFO     root:validator.py:25 Valid link: https://play.google.com/?hl=uk&tab=w8
INFO     root:validator.py:25 Valid link: https://www.youtube.com/?tab=w1
INFO     root:validator.py:25 Valid link: https://news.google.com/?tab=wn
INFO     root:validator.py:25 Valid link: https://mail.google.com/mail/?tab=wm
INFO     root:validator.py:25 Valid link: https://drive.google.com/?tab=wo
INFO     root:validator.py:25 Valid link: https://www.google.com.ua/intl/uk/about/products?tab=wh
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/history/optout?hl=uk
INFO     root:validator.py:25 Valid link: https://accounts.google.com/ServiceLogin?hl=uk&passive=true&continue=https://www.google.com/&ec=GAZAAQ
INFO     root:validator.py:25 Valid link: http://www.google.com.ua/intl/uk/services/
INFO     root:validator.py:25 Valid link: https://www.google.com/setprefdomain?prefdom=UA&prev=https://www.google.com.ua/&sig=K_IBatk0BNkQT8cQGkynPksvF3esQ%3D
INFO     root:interface.py:63 All valid links are recorded in the file 'valid_links.txt'
INFO     root:interface.py:64 Written all invalid links in the file 'broken_links.txt'
INFO     root:PDFParser.py:26 Received all links from the pdf file
INFO     root:test_pdf_parser.py:18 test_get_links_returns_list
INFO     root:PDFParser.py:26 Received all links from the pdf file
INFO     root:test_pdf_parser.py:28 test_len_list_of_links_more_than_0
ERROR    root:PDFParser.py:28 Error when receiving links from a pdf file: [Errno 2] No such file or directory: '/path/to/nonexistent.pdf'
INFO     root:test_pdf_parser.py:42 test_get_links_with_exception
INFO     root:test_saver.py:35 test_save_to_file
INFO     root:test_validator.py:17 test_get_valid_url
WARNING  root:validator.py:31 Invalid link: https://translater.google.com/
WARNING  root:validator.py:31 Invalid link: https://uk.lipsum.cor/
WARNING  root:validator.py:31 Invalid link: https://www.dyoutuber.com/
INFO     root:validator.py:25 Valid link: https://medium.com/
INFO     root:validator.py:25 Valid link: https://www.olx.ua/uk
INFO     root:test_validator.py:35 test_validate_links
INFO     root:test_validator.py:49 test_check_file_exists
INFO     root:test_validator.py:63 test_is_valid_url
